[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Netlify will automatically handle Next.js routing

[[plugins]]
  package = "@netlify/plugin-nextjs"
